### ISSUE TITLE
[vm-other]

### ISSUE THREAD

**Issue by cskimpel** [SoftwareEngineeringToolDemos/ICSE-2010-ConQat#6]
Ubuntu in the VM has a timeout function that locks the desktop after a few minutes of inactivity. It requires a password to log in.

I do not know what the password is. I suppose I could reset it to something that I know, but I am not familiar with how to do that in Ubuntu.

**Comment by vinay92** [comment]
The password is conqat.

**Comment by vinay92** [comment]
As discussed in class, for this problem, the proposed solution is to keep the password same as the tool name which is currently available in the VM. @CaptainEmerson , Dr. Emerson, since it was previously mentioned in Piazza that the password should be the same as the tool name, I have put all lowercase password. But the tool name has two upper case letters. Would this be fine since it is not allowing me to change the password only when the case differs. I have disabled the locking as well.
